service: alpha-project

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: graphql
          method: get
      - http:
          path: graphql
          method: post
  graphiql:
    handler: src/handler.graphiql
    events:
      - http:
          path: graphiql
          method: get
    environment:
      STAGE: ${self:custom.stage}

