version: '3'
services:
  sls:
    image: node:6
    restart: unless-stopped
    volumes:
      - ${PROJECT_ABSOLUTE_PATH}:/usr/app:delegated
    environment:
      STAGE: ${STAGE}
      SLS_DEBUG: '*'
    working_dir: /usr/app
    command: ./docker/sls/start.sh
    ports:
      - 80:3000
